### ISSUE TITLE
use []byte or custom type for pubsub Message data

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloudevents-go#49]
## Expected Behavior

```go
// Option 1
type Message struct {
	Data        []byte        `json:"data,omitempty"`        // The binary data in the message.
}
```

```go
// Option 2
type Message struct {
	Data        ByteData        `json:"data,omitempty"`        // The binary data in the message.
}
```

## Actual Behavior

```go
type Message struct {
	Data        *string        `json:"data,omitempty"`        // The binary data in the message.
}
```

## Details

The choice to use a string was also made in our HTTP/REST libraries. We did not respect the [”format”: “byte”](https://github.com/googleapis/google-api-go-client/blob/7570391cc25b18bef231a82fadc38f78fa76265c/pubsub/v1/pubsub-api.json#L1779). We have an [open issue](https://github.com/googleapis/google-api-go-client/issues/346) around how it would have been nice to generate these types as []byte.

Option 2 might be nice do you could provide a custom mashaller for the type that auto encodes/decodes base64 values so the user of this library does not have to.

**Comment by grant** [comment]
Ideally we modify quicktype to support generating `[]bytes` with a native JSON schema base64 type.

https://github.com/quicktype/quicktype/issues/1317

---

An alternative would be to look for all the `"binaryEncoding": "base64"` fields in our schemas and convert the respective golang field types.

**Comment by grant** [comment]
The implementation of this will be rather complicated. I'll have to check with @grayside on how we can make a 

This is one of the cases where using proto/protoc would be nice instead of jsonschema. Proto generation produces a `[]byte` appropriately. There are some upstream jsonschema & jsonschema tooling fixes we'd need to do to natively generate the same base64 `[]byte` from jsonschema.

https://github.com/googleapis/google-cloudevents-go/blob/990cec12da31c4c1f23059ab3163d4070c2c0008/src/google/events/cloud/pubsub/v1/data.pb.go#L109

**Comment by grant** [comment]
Here are the instances of protos with bytes:

- Cloud Build: repeated bytes build_step_outputs
- Cloud Build: bytes value
- Cloud Firestore: bytes bytes_value
- Cloud Pub/Sub: bytes data
- Cloud Scheduler: bytes custom_data

**Comment by grant** [comment]
Should be fixed with the above PR! :)
