### ISSUE TITLE
Refactor hard to use types map[string]map[string]interface{}

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloudevents-go#51]
## Expected Behavior

```go
type Foo string {
   Bar AHelperType
}
```

## Actual Behavior

```go
type Foo string {
   Bar map[string]map[string]interface{}
}
```

## Details

There are a few instances of `map[string]map[string]interface{}` being used. I wonder if a nicer type could be generated to make using these fields easier to use and construct? It is unclear to me why things like [Claims](https://pkg.go.dev/github.com/googleapis/google-cloudevents-go/cloud/audit/v1#Claims) embed this type. I think Claims itself could just be a `map[string]interface{}`? Example of where we do something similar in the client libraries: https://pkg.go.dev/google.golang.org/api/idtoken#Payload.

**Comment by grant** [comment]
I've modified the post-generator to simplify the `map[string]map[string]interface{}` to `map[string]interface{}`, which should be more accurate and easier to use.

Some of these types are because our proto defines the field as a `google.protobuf.Struct`.

We may need to get further feedback on the types in use as more events are supported.

---

Fixed with https://github.com/googleapis/google-cloudevents-go/pull/53
